package Modelo;
// Generated 3 mar. 2022 17:58:56 by Hibernate Tools 4.3.1



/**
 * Carrito generated by hbm2java
 */
public class Carrito  implements java.io.Serializable {


     private int idCarrito;
     private Producto producto;
     private Usuario usuario;
     private int cantidad;

    public Carrito() {
    }

    public Carrito(int idCarrito, Producto producto, Usuario usuario, int cantidad) {
       this.idCarrito = idCarrito;
       this.producto = producto;
       this.usuario = usuario;
       this.cantidad = cantidad;
    }
   
    public int getIdCarrito() {
        return this.idCarrito;
    }
    
    public void setIdCarrito(int idCarrito) {
        this.idCarrito = idCarrito;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


