package Modelo;
// Generated 3 mar. 2022 17:58:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CategoriaProducto generated by hbm2java
 */
public class CategoriaProducto  implements java.io.Serializable {


     private int idCategoriaProducto;
     private String descripcion;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public CategoriaProducto() {
    }

    public CategoriaProducto(int idCategoriaProducto, String descripcion, Set<Producto> productos) {
       this.idCategoriaProducto = idCategoriaProducto;
       this.descripcion = descripcion;
       this.productos = productos;
    }
   
    public int getIdCategoriaProducto() {
        return this.idCategoriaProducto;
    }
    
    public void setIdCategoriaProducto(int idCategoriaProducto) {
        this.idCategoriaProducto = idCategoriaProducto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }

    @Override
    public String toString() {
        return descripcion;
    }

}


