package Modelo;
// Generated 3 mar. 2022 17:58:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MetodoPago generated by hbm2java
 */
public class MetodoPago  implements java.io.Serializable {


     private int idMetodoPago;
     private String descripcion;
     private Set<Orden> ordens = new HashSet<Orden>(0);

    public MetodoPago() {
    }

	
    public MetodoPago(int idMetodoPago, String descripcion) {
        this.idMetodoPago = idMetodoPago;
        this.descripcion = descripcion;
    }
    public MetodoPago(int idMetodoPago, String descripcion, Set<Orden> ordens) {
       this.idMetodoPago = idMetodoPago;
       this.descripcion = descripcion;
       this.ordens = ordens;
    }
   
    public int getIdMetodoPago() {
        return this.idMetodoPago;
    }
    
    public void setIdMetodoPago(int idMetodoPago) {
        this.idMetodoPago = idMetodoPago;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Orden> getOrdens() {
        return this.ordens;
    }
    
    public void setOrdens(Set<Orden> ordens) {
        this.ordens = ordens;
    }




}


